### ISSUE TITLE
Can my k30i be flashed with this kernel please?

### ISSUE THREAD

**Issue by QQ1071378751** [EndCredits/kernel_xiaomi_sm7250#5]
System: MIUI 13 Android 12 
Kernel: 4.19
I want to experience the zram compression algorithm lz4, but the official kernel only supports lzo.
So I want to flash it.

**Comment by EndCredits** [comment]
Are you sure you wrote it right? I don't think MIUI 13 has A13.

-------

阿哲，没写错吧，MIUI13 有 Android 13 吗

**Comment by QQ1071378751** [comment]
抱歉，我写错了。是安卓12。

**Comment by EndCredits** [comment]
I don't recommend using this kernel on MIUI, there is a high chance that it won't work properly.If you want to experience lz4, it is recommended to choose custom ROM.

-----

这东西在 MIUI 上多半跑不起来，最好不要用，想试试 lz4 的话最好选一个类原生

**Comment by QQ1071378751** [comment]
我知道了，谢谢大佬。
